apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  erlang-cookie: {{ .Values.rabbitmq.erlangCookie | b64enc }}
  username: {{ .Values.rabbitmq.default_user | b64enc }}
  password: {{ .Values.rabbitmq.default_pass | b64enc }}
