apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rabbitmq
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
    - name: amqp
      port: {{ .Values.service.port }}
      targetPort: amqp
    - name: management
      port: {{ .Values.service.managementPort }}
      targetPort: management
  clusterIP: None
  selector:
    app: {{ .Chart.Name }}
